### Spring properties
# Service registers under this name
spring:
  application:
    name: taipan-ms

# Discovery Server Access
eureka:
  instance:
    metadataMap:
      type: extractor
      friendlyname: TAIPAN
  client:
    serviceUrl:
      defaultZone: http://@eureka.hostname@:@eureka.port@/eureka/

# HTTP Server (Tomcat) Port
server: 
  port: 2228

# Disable Spring Boot's "Whitelabel" default error page, so we can use our own
error:
  whitelabel:
    enabled: false
    
taipan:
  hostserver: @taipan.hostserver@
  port: @taipan.port@
  
