### Spring properties
# Service registers under this name
spring:
  application:
    name: executer-ms

# Discovery Server Access
eureka:
  instance:
    metadataMap:
      type: executer
      friendlyname: Executer
  client:
    serviceUrl:
      defaultZone: http://@eureka.hostname@:@eureka.port@/eureka/

# HTTP Server (Tomcat) Port
server: 
  port: 2500

# Disable Spring Boot's "Whitelabel" default error page, so we can use our own
error:
  whitelabel:
    enabled: false
