# Service registers under this name
# Control the InternalResourceViewResolver:
spring:
  application:
    name: webclient

# Discovery Server Access
eureka:
  instance:
    metadataMap:
      type: webclient
      friendlyname: Webclient
  client:
    serviceUrl:
      defaultZone: http://@eureka.hostname@:@eureka.port@/eureka/

# Disable Spring Boot's "Whitelabel" default error page, so we can use our own
error:
  whitelabel:
    enabled: false
    
#server port      
server:
  port: 9090

#zuul route
zuul:
  routes:
    chatbot:
      path: /CHATBOT/**
      serviceId: CHATBOT
    repo:
      path: /REPO-MS/**
      serviceId: REPO-MS
    executer:
      path: /EXECUTER-MS/**
      serviceId: EXECUTER-MS
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: THREAD
          thread:
            timeoutInMilliseconds: 10000
