### Spring properties
# Service registers under this name
spring:
  application:
    name: ensemble-ms

# Discovery Server Access
eureka:
  instance:
    metadataMap:
      type: ensemble
      friendlyname: Ensemble
  client:
    serviceUrl:
      defaultZone: http://@eureka.hostname@:@eureka.port@/eureka/

# HTTP Server (Tomcat) Port
server: 
  port: 2400

# Disable Spring Boot's "Whitelabel" default error page, so we can use our own
error:
  whitelabel:
    enabled: false
