# Configure this Discovery Server
eureka:
  instance:
    hostname: @eureka.hostname@
  client: #Not a client
    registerWithEureka: false
    fetchRegistry: false

# HTTP (Tomcat) port
server:
  port: @eureka.port@   
